"""
Generate book descriptions from chapter summaries using OpenAI,
then output SQL UPDATE statements for public.books_list.description.

For each book in data/summaries/{book_id}/:
  - Combine all chapter titles + summaries
  - Ask GPT-4o for a 2-3 sentence Indonesian description
  - Output: UPDATE public.books_list SET description = '...' WHERE id = {book_id};

Usage:
    python generate_descriptions_sql.py             # all books
    python generate_descriptions_sql.py --book 290  # single book (test)
    python generate_descriptions_sql.py --output my.sql
"""
import argparse
import json
import os
import re
import time
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI, RateLimitError

load_dotenv()

BASE_DIR     = Path(__file__).parent
SUMMARIES_DIR = BASE_DIR / "data" / "summaries"
OUTPUT_FILE  = BASE_DIR / "update_descriptions.sql"

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def load_summaries(book_dir: Path) -> list[dict]:
    """Load and sort all chapter summary JSONs for a book."""
    files = sorted(book_dir.glob("chapter_*.json"),
                   key=lambda p: int(re.search(r'\d+', p.stem).group()))
    summaries = []
    for f in files:
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
            summaries.append(d)
        except Exception:
            pass
    return summaries


def build_prompt(book_id: str, summaries: list[dict]) -> str:
    parts = []
    for s in summaries[:10]:  # max 10 chapters to keep prompt short
        title = s.get("title", "").strip()
        text  = s.get("summary", "").strip()[:400]
        if title or text:
            parts.append(f"- {title}: {text}")

    chapters_text = "\n".join(parts)
    return f"""Berdasarkan ringkasan bab-bab berikut dari sebuah buku (ID: {book_id}):

{chapters_text}

Tuliskan deskripsi buku dalam Bahasa Indonesia, 2-3 kalimat saja. 
Jelaskan isi/tema utama buku secara menarik agar pembaca ingin membacanya.
Jangan sebutkan nomor bab atau kata "buku ini memiliki X bab".
Langsung tulis deskripsinya saja, tanpa awalan seperti "Buku ini" kalau bisa diganti dengan kalimat yang lebih menarik."""


def call_openai_with_retry(prompt: str, max_retries: int = 6) -> str:
    delay = 10
    for attempt in range(1, max_retries + 1):
        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                max_tokens=256,
                temperature=0.7,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content.strip()
        except RateLimitError as e:
            if attempt == max_retries:
                raise
            m = re.search(r'try again in (\d+\.?\d*)s', str(e))
            wait = float(m.group(1)) + 2 if m else delay
            print(f"    [rate limit] waiting {wait:.0f}s ...")
            time.sleep(wait)
            delay = min(delay * 2, 120)
    return ""


def escape_sql(s: str) -> str:
    return s.replace("'", "''")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--book",   type=str, default=None, help="Single book ID to process")
    parser.add_argument("--output", type=str, default=str(OUTPUT_FILE), help="Output SQL file path")
    args = parser.parse_args()

    out_path = Path(args.output)

    # Collect book dirs to process
    if args.book:
        book_dirs = [SUMMARIES_DIR / args.book]
        if not book_dirs[0].exists():
            print(f"ERROR: No summaries found for book {args.book}")
            return
    else:
        book_dirs = sorted(
            [d for d in SUMMARIES_DIR.iterdir() if d.is_dir()],
            key=lambda d: d.name
        )

    print(f"Processing {len(book_dirs)} books...\n")

    lines = [
        "-- Book descriptions generated by GPT-4o",
        "-- Source: data/summaries/{book_id}/chapter_*.json",
        "",
    ]

    ok = fail = skipped = 0

    for i, book_dir in enumerate(book_dirs, 1):
        book_id = book_dir.name
        summaries = load_summaries(book_dir)

        if not summaries:
            print(f"[{i}/{len(book_dirs)}] {book_id}: no summaries, skip")
            skipped += 1
            continue

        print(f"[{i}/{len(book_dirs)}] {book_id} ({len(summaries)} chapters)...", end=" ", flush=True)

        try:
            prompt = build_prompt(book_id, summaries)
            description = call_openai_with_retry(prompt)
            description = escape_sql(description)
            lines.append(f"UPDATE public.books_list SET description = '{description}' WHERE id = {book_id};")
            print("OK")
            ok += 1
        except Exception as e:
            print(f"ERROR: {e}")
            fail += 1

        # Throttle between requests
        if i < len(book_dirs):
            time.sleep(1)

    output = "\n".join(lines)
    out_path.write_text(output, encoding="utf-8")

    print(f"\nSaved: {out_path.name}")
    print(f"  OK      : {ok}")
    print(f"  Skipped : {skipped}")
    if fail:
        print(f"  Failed  : {fail}")


if __name__ == "__main__":
    main()
