-- Gutenberg books INSERT
-- Generated from D:\b_outside\a_intesa_global_technology\Storify\Storify-Insights\api\ai-audiobook-agent\gutenberg_books\plain_text
-- Total: 92 files

INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9991, 'The City of God, Volume I', 'Saint of Hippo Augustine', 'Religion');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99910, 'Middlemarch', 'George Eliot', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (999100, 'Leaves of Grass', 'Walt Whitman', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99911, 'Little Women; Or, Meg, Jo, Beth, and Amy', 'Louisa May Alcott', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99912, 'The Blue Castle: a novel', 'L. M. Montgomery', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99913, 'My Life — Volume 1', 'Richard Wagner', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99914, 'The Enchanted April', 'Elizabeth Von Arnim', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99915, 'History of Tom Jones, a Foundling', 'Henry Fielding', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99916, 'The Expedition of Humphry Clinker', 'T. Smollett', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99917, 'The Adventures of Ferdinand Count Fathom — Complete', 'T. Smollett', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99918, 'Cranford', 'Elizabeth Cleghorn Gaskell', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99919, 'Twenty years after', 'Alexandre Dumas', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9992, 'Frankenstein; or, the modern prometheus', 'Mary Wollstonecraft Shelley', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99920, 'The Adventures of Roderick Random', 'T. Smollett', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99921, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99922, 'The Picture of Dorian Gray', 'Oscar Wilde', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99923, 'Crime and Punishment', 'Fyodor Dostoyevsky', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99924, 'The strange case of Dr. Jekyll and Mr. Hyde', 'Robert Louis Stevenson', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99925, 'Jane Eyre: An Autobiography', 'Charlotte Brontë', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99926, 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99927, 'Natural History of the Mammalia of India and Ceylon', 'Robert Armitage Sterndale', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99928, 'Les Misérables', 'Victor Hugo', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99929, 'The Prince', 'Niccolò Machiavelli', 'Leadership');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9993, 'Moby Dick; Or, The Whale', 'Herman Melville', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99930, 'Dictionnaire raisonné de l''architecture française du XIe au XVIe siècle - Tome 1 - (A)', 'Eugène-Emmanuel Viollet-le-Duc', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99931, 'The Brothers Karamazov', 'Fyodor Dostoyevsky', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99932, 'The Importance of Being Earnest: A Trivial Comedy for Serious People', 'Oscar Wilde', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99933, 'Dracula', 'Bram Stoker', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99934, 'The Count of Monte Cristo', 'Alexandre Dumas', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99935, '警世通言', 'Menglong Feng', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99936, 'A Doll''s House : a play', 'Henrik Ibsen', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99937, 'A Tale of Two Cities', 'Charles Dickens', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99938, 'The King in Yellow', 'Robert W. Chambers', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99939, 'White nights, and other stories', 'Fyodor Dostoyevsky', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9994, 'Pride and Prejudice', 'Jane Austen', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99940, 'A Cyclopaedia of Canadian Biography: Being Chiefly Men of the Time', '', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99941, 'The golden journey of Mr. Paradyne', 'William John Locke', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99942, 'Bleak House', 'Charles Dickens', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99944, 'Adventures of Huckleberry Finn', 'Mark Twain', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99945, 'Ulysses', 'James Joyce', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99946, 'Great Expectations', 'Charles Dickens', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99947, 'Thus Spake Zarathustra: A Book for All and None', 'Friedrich Wilhelm Nietzsche', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99948, 'The weird of the wanderer', 'Frederick Rolfe', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99949, 'Metamorphosis', 'Franz Kafka', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9995, 'Wuthering Heights', 'Emily Brontë', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99950, 'The divine comedy', 'Dante Alighieri', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99951, 'A Modest Proposal', 'Jonathan Swift', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99952, 'The Outline of History: Being a Plain History of Life and Mankind', 'H. G. Wells', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99953, 'War and Peace', 'graf Leo Tolstoy', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99954, 'Anna Karenina', 'graf Leo Tolstoy', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99955, 'The Confessions of St. Augustine', 'Saint of Hippo Augustine', 'Religion');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99956, 'Leviathan', 'Thomas Hobbes', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99957, 'Beowulf: An Anglo-Saxon Epic Poem', '', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99958, 'Grimms'' Fairy Tales', 'Jacob Grimm', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99959, 'The Yellow Wallpaper', 'Charlotte Perkins Gilman', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9996, 'Romeo and Juliet', 'William Shakespeare', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99961, 'Meditations', 'Emperor of Rome Marcus Aurelius', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99962, 'Peter Pan', 'J. M. Barrie', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99963, 'Noli Me Tangere', 'José Rizal', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99964, 'Simple Sabotage Field Manual', 'United States. Office of Strategic Services', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99965, 'Anne of Green Gables', 'L. M. Montgomery', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99966, 'The Scarlet Letter', 'Nathaniel Hawthorne', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99967, 'Zoonomia; Or, the Laws of Organic Life, Vol. I', 'Erasmus Darwin', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99968, 'The Adventures of Tom Sawyer, Complete', 'Mark Twain', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9997, 'Alice''s Adventures in Wonderland', 'Lewis Carroll', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99970, 'Walden, and On The Duty Of Civil Disobedience', 'Henry David Thoreau', 'Self-Improvement');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99971, 'The Odyssey', 'Homer', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99972, 'The Republic', 'Plato', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99973, 'Oedipus King of Thebes', 'Sophocles', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99975, 'The Mayflower, January, 1905', 'Various', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99976, 'The lesser Key of Solomon, Goetia, the book of evil spirits', '', 'Religion');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99977, 'Notes from the Underground', 'Fyodor Dostoyevsky', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99978, 'The Outline of Science, Vol. 1 (of 4)', 'J. Arthur Thomson', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99979, 'Treasure Island', 'Robert Louis Stevenson', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9998, 'The Complete Works of William Shakespeare', 'William Shakespeare', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99980, 'Diccionario Ingles-Español-Tagalog', 'Sofronio G. Calderón', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99981, 'The King James Version of the Bible', '', 'Religion');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99982, '1066 and all that', 'Walter Carruthers Sellar', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99983, 'Gulliver''s Travels into Several Remote Nations of the World', 'Jonathan Swift', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99984, 'The Romance of Lust: A classic Victorian erotic novel', 'Anonymous', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99985, 'Spenser''s The Faerie Queene, Book I', 'Edmund Spenser', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99987, 'A Study in Scarlet', 'Arthur Conan Doyle', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (9999, 'A Room with a View', 'E. M. Forster', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99990, 'The Wonderful Wizard of Oz', 'L. Frank Baum', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99991, 'The Boy Travellers in The Russian Empire', 'Thomas Wallace Knox', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99992, 'Moby Multiple Language Lists of Common Words', 'Grady Ward', 'Education');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99993, 'The Souls of Black Folk', 'W. E. B. Du Bois', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99995, 'Second Treatise of Government', 'John Locke', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99996, 'Arrian on coursing', 'Arrian', 'Lifestyle');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99997, 'Peter Pan', 'J. M. Barrie', 'Fiction');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99998, 'Reise in die Aequinoctial-Gegenden des neuen Continents. Band 2.', 'Alexander von Humboldt', 'History');
INSERT INTO public.books_list (id, fix_title, author, category) VALUES (99999, 'Beyond Good and Evil', 'Friedrich Wilhelm Nietzsche', 'Education');